### ISSUE TITLE
Latest tedge-container-bundle is only available for arm64

### ISSUE THREAD

**Issue by ck-c8y** [thin-edge/tedge-container-bundle#57]
The latest tedge-container-bundle is only available for arm64:

docker pull ghcr.io/thin-edge/tedge-container-bundle:latest

**Comment by reubenmiller** [comment]
Ok, this is strange. We didn't do an intentional release yesterday (due to a problem discovered with the workflow changes in thin-edge.io 1.4.0). I'll try republishing the last tag.

@ck-c8y But generally speaking this is why using "latest" tag is generally a bad idea, as you can accidentally get unexpected changes.

**Comment by reubenmiller** [comment]
The last tag `20241204.1247` has now been rebuilt and it has the "latest" tag again.

```
docker pull ghcr.io/thin-edge/tedge-container-bundle:20241204.1247
```
